apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-deploy
  name: {{ .Release.Name }}-deploy
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deploy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deploy
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: flaskex
        resources:
          requests:
            memory: {{ .Values.resources.memoryRequest }}
            cpu: {{ .Values.resources.cpuRequest }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        
